### ISSUE TITLE
Feedback on Assignment

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/intro-R-Python-avikalsingh1#1]
Hi Avikal,

Great work on the assignment. Some minor feedback:

It's important to have authorship on all notebooks (first name, last name)
I would like to see some markdown formatting for the title and section headers (use "#" Title, and "##" Section titles).
These changes make the notebook more readable and shareable.

I am giving you full credit, contingent on you fixing these minor issues by September 15th.
-Greg

**Comment by avikalsingh1** [comment]
Thank you for correcting me Sir, 
I have done the needful changes in both of the repositories as per your suggestion apart from that if any other changes are to be done then please inform me regarding that.
